<a href="https://colab.research.google.com/github/IDGAF-69/data-science-W1/blob/main/week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Create a numpy array of size 2 x 2
arr_2x2 = np.array([[5, 10],
                    [15, 20]])
print("--- 1. 2x2 Array ---")
print(arr_2x2)
print("Shape:", arr_2x2.shape)


# 2. Create a random numpy array of size 3 x 4
# (Values will be random floats between 0.0 and 1.0)
arr_random_3x4 = np.random.rand(3, 4)
print("\n--- 2. Random 3x4 Array ---")
print(arr_random_3x4)
print("Shape:", arr_random_3x4.shape)


# 3. Create a numpy array of ones and a numpy array of zeroes
# (Let's use a 2x3 shape as an example)
shape_example = (2, 3)
arr_ones = np.ones(shape_example)
arr_zeros = np.zeros(shape_example)
print("\n--- 3. Arrays of Ones and Zeros ---")
print("Ones:")
print(arr_ones)
print("Zeros:")
print(arr_zeros)


# 4. Create a random numpy array of size 6x3 and transpose it
arr_6x3 = np.random.rand(6, 3)
arr_transposed = arr_6x3.T
print("\n--- 4. Transposed Array ---")
print("Original 6x3 Shape:", arr_6x3.shape)
# print("Original Array:\n", arr_6x3) # Uncomment to see the original
print("Transposed 3x6 Shape:", arr_transposed.shape)
# print("Transposed Array:\n", arr_transposed) # Uncomment to see the result


# 5. Create two random numpy arrays (n x p and p x m) and compute the dot product
# Let's define n, p, and m
n = 4  # rows of A
p = 2  # cols of A / rows of B
m = 5  # cols of B

arr_nxp = np.random.rand(n, p) # Shape (4, 2)
arr_pxm = np.random.rand(p, m) # Shape (2, 5)

# Compute the dot product
dot_product = np.dot(arr_nxp, arr_pxm)
# An alternative syntax is: dot_product = arr_nxp @ arr_pxm

print("\n--- 5. Dot Product ---")
print("Shape of A (n x p):", arr_nxp.shape)
print("Shape of B (p x m):", arr_pxm.shape)
print("Shape of Dot Product (n x m):", dot_product.shape)
print("Dot Product Result:\n", dot_product)

--- 1. 2x2 Array ---
[[ 5 10]
 [15 20]]
Shape: (2, 2)

--- 2. Random 3x4 Array ---
[[0.78429058 0.19042798 0.10332329 0.57966631]
 [0.05670252 0.71079476 0.14046855 0.04888788]
 [0.90183584 0.16743425 0.85922801 0.48911253]]
Shape: (3, 4)

--- 3. Arrays of Ones and Zeros ---
Ones:
[[1. 1. 1.]
 [1. 1. 1.]]
Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

--- 4. Transposed Array ---
Original 6x3 Shape: (6, 3)
Transposed 3x6 Shape: (3, 6)

--- 5. Dot Product ---
Shape of A (n x p): (4, 2)
Shape of B (p x m): (2, 5)
Shape of Dot Product (n x m): (4, 5)
Dot Product Result:
 [[0.1688855  0.38140873 0.20324204 0.20534322 0.04458311]
 [0.36698213 0.74464085 0.33200138 0.25745678 0.07305661]
 [0.49801706 1.02877276 0.47432415 0.39032019 0.10430858]
 [0.47526758 1.0265565  0.51099936 0.47293091 0.11221992]]
